package systemdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

import java.io.Serializable;

/**
 * Entity mapped to table "ACTION_LOGIN".
 */
@Entity
public class Login implements Serializable {
    private static final long serialVersionUID=1L;
    @Id(autoincrement = true)
    private Long id;
    @NotNull
    private Integer memberid;
    private String code;
    private String name;
    private String commission;
    private String khreferralcode;
    private String phonenumber;
    private String nickname;
    @NotNull
    private Integer age;
    private String photo;
    private String city;
    @NotNull
    private double latitude;
    @NotNull
    private double longitude;
    private String address;
    private String sex;
    private String idcard;
    @NotNull
    private int drivercount;
    @NotNull
    private int viplevel;
    private String version;
    @NotNull
    private int integral;
    @NotNull
    private float balance;
    @NotNull
    private float couponsbalance;
    @NotNull
    private float startprice;
    @NotNull
    private Integer upmemberid;
    @NotNull
    private int membertypeid;
    private String membertypename;
    private String phonetype;
    private String alipayaccout;
    private String weiXinid;
    private String weixinaccount;
    private String bankname;
    private String bankaccount;
    private String bankidcard;
    private String bankusername;
    private String jobs;
    private String icename;
    private String icephone;
    private String complain;
    private String areacode;
    private String plate;
    @NotNull
    private int num;
    @Generated(hash = 301737029)
    public Login(Long id, @NotNull Integer memberid, String code, String name, String commission,
                 String khreferralcode, String phonenumber, String nickname, @NotNull Integer age,
                 String photo, String city, double latitude, double longitude, String address, String sex,
                 String idcard, int drivercount, int viplevel, String version, int integral, float balance,
                 float couponsbalance, float startprice, @NotNull Integer upmemberid, int membertypeid,
                 String membertypename, String phonetype, String alipayaccout, String weiXinid,
                 String weixinaccount, String bankname, String bankaccount, String bankidcard,
                 String bankusername, String jobs, String icename, String icephone, String complain,
                 String areacode, String plate, int num) {
        this.id = id;
        this.memberid = memberid;
        this.code = code;
        this.name = name;
        this.commission = commission;
        this.khreferralcode = khreferralcode;
        this.phonenumber = phonenumber;
        this.nickname = nickname;
        this.age = age;
        this.photo = photo;
        this.city = city;
        this.latitude = latitude;
        this.longitude = longitude;
        this.address = address;
        this.sex = sex;
        this.idcard = idcard;
        this.drivercount = drivercount;
        this.viplevel = viplevel;
        this.version = version;
        this.integral = integral;
        this.balance = balance;
        this.couponsbalance = couponsbalance;
        this.startprice = startprice;
        this.upmemberid = upmemberid;
        this.membertypeid = membertypeid;
        this.membertypename = membertypename;
        this.phonetype = phonetype;
        this.alipayaccout = alipayaccout;
        this.weiXinid = weiXinid;
        this.weixinaccount = weixinaccount;
        this.bankname = bankname;
        this.bankaccount = bankaccount;
        this.bankidcard = bankidcard;
        this.bankusername = bankusername;
        this.jobs = jobs;
        this.icename = icename;
        this.icephone = icephone;
        this.complain = complain;
        this.areacode = areacode;
        this.plate = plate;
        this.num = num;
    }
    @Generated(hash = 1827378950)
    public Login() {
    }
    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public Integer getMemberid() {
        return this.memberid;
    }
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }
    public String getCode() {
        return this.code;
    }
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getCommission() {
        return this.commission;
    }
    public void setCommission(String commission) {
        this.commission = commission;
    }
    public String getKhreferralcode() {
        return this.khreferralcode;
    }
    public void setKhreferralcode(String khreferralcode) {
        this.khreferralcode = khreferralcode;
    }
    public String getPhonenumber() {
        return this.phonenumber;
    }
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }
    public String getNickname() {
        return this.nickname;
    }
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public Integer getAge() {
        return this.age;
    }
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getPhoto() {
        return this.photo;
    }
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getCity() {
        return this.city;
    }
    public void setCity(String city) {
        this.city = city;
    }
    public double getLatitude() {
        return this.latitude;
    }
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
    public double getLongitude() {
        return this.longitude;
    }
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    public String getAddress() {
        return this.address;
    }
    public void setAddress(String address) {
        this.address = address;
    }
    public String getSex() {
        return this.sex;
    }
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getIdcard() {
        return this.idcard;
    }
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }
    public int getDrivercount() {
        return this.drivercount;
    }
    public void setDrivercount(int drivercount) {
        this.drivercount = drivercount;
    }
    public int getViplevel() {
        return this.viplevel;
    }
    public void setViplevel(int viplevel) {
        this.viplevel = viplevel;
    }
    public String getVersion() {
        return this.version;
    }
    public void setVersion(String version) {
        this.version = version;
    }
    public int getIntegral() {
        return this.integral;
    }
    public void setIntegral(int integral) {
        this.integral = integral;
    }
    public float getBalance() {
        return this.balance;
    }
    public void setBalance(float balance) {
        this.balance = balance;
    }
    public float getCouponsbalance() {
        return this.couponsbalance;
    }
    public void setCouponsbalance(float couponsbalance) {
        this.couponsbalance = couponsbalance;
    }
    public float getStartprice() {
        return this.startprice;
    }
    public void setStartprice(float startprice) {
        this.startprice = startprice;
    }
    public Integer getUpmemberid() {
        return this.upmemberid;
    }
    public void setUpmemberid(Integer upmemberid) {
        this.upmemberid = upmemberid;
    }
    public int getMembertypeid() {
        return this.membertypeid;
    }
    public void setMembertypeid(int membertypeid) {
        this.membertypeid = membertypeid;
    }
    public String getMembertypename() {
        return this.membertypename;
    }
    public void setMembertypename(String membertypename) {
        this.membertypename = membertypename;
    }
    public String getPhonetype() {
        return this.phonetype;
    }
    public void setPhonetype(String phonetype) {
        this.phonetype = phonetype;
    }
    public String getAlipayaccout() {
        return this.alipayaccout;
    }
    public void setAlipayaccout(String alipayaccout) {
        this.alipayaccout = alipayaccout;
    }
    public String getWeiXinid() {
        return this.weiXinid;
    }
    public void setWeiXinid(String weiXinid) {
        this.weiXinid = weiXinid;
    }
    public String getWeixinaccount() {
        return this.weixinaccount;
    }
    public void setWeixinaccount(String weixinaccount) {
        this.weixinaccount = weixinaccount;
    }
    public String getBankname() {
        return this.bankname;
    }
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }
    public String getBankaccount() {
        return this.bankaccount;
    }
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount;
    }
    public String getBankidcard() {
        return this.bankidcard;
    }
    public void setBankidcard(String bankidcard) {
        this.bankidcard = bankidcard;
    }
    public String getBankusername() {
        return this.bankusername;
    }
    public void setBankusername(String bankusername) {
        this.bankusername = bankusername;
    }
    public String getJobs() {
        return this.jobs;
    }
    public void setJobs(String jobs) {
        this.jobs = jobs;
    }
    public String getIcename() {
        return this.icename;
    }
    public void setIcename(String icename) {
        this.icename = icename;
    }
    public String getIcephone() {
        return this.icephone;
    }
    public void setIcephone(String icephone) {
        this.icephone = icephone;
    }
    public String getComplain() {
        return this.complain;
    }
    public void setComplain(String complain) {
        this.complain = complain;
    }
    public String getAreacode() {
        return this.areacode;
    }
    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }
    public String getPlate() {
        return this.plate;
    }
    public void setPlate(String plate) {
        this.plate = plate;
    }
    public int getNum() {
        return this.num;
    }
    public void setNum(int num) {
        this.num = num;
    }

}
