package systemdb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "ORDER".
 */
//@Entity
public class Order implements Serializable {
   // private static final long serialVersionUID=1L;
    //@Id
    private Long id;
    //@NotNull
    private int ordertime;
   // @NotNull
    private Integer orderid;
    private String code;
    //@NotNull
    private int type;
   // @NotNull
    private int status;
    //@NotNull
    private float price;
   // @NotNull
    private float tip;
   // @NotNull
    private float startingcost;
    //@NotNull
    private float settlementcost;
   // @NotNull
    private float discountcost;
    /** Not-null value. */
    private String waitingtime;
   // @NotNull
    private float waitingcost;
    private String registrationId;
    private String photo;
    /** Not-null value. */
    private String startingtime;
    private String beginplacedescription;
    private String beginlocation;
    /** Not-null value. */
    private String arrivingtime;
    private String endplacedescription;
    private String endlocation;
    private Integer driverid;
    private String drivername;
    private String driverphone;
    private String drivercode;
    private Integer memberid;
    private String memberphone;
    private String membername;
    //@NotNull
    private int ordertype;
    /** Not-null value. */
    private String totaltime;
    private String memo;
    private String goods;
   // @NotNull
    private int isevaluation;
    private String paytype;
    //@NotNull
    private int score;
   // @NotNull
    private float distance;
    //@NotNull
    private float distancecost;
    private String description;
    private String plate;
    private String carmodel;
    private String addTime;
    private String beginTime;
    private String ordertypename;
    private String bookingtime;
    //@NotNull
    private int rownumber;
   // @NotNull
    private float nightcost;
   // @NotNull
    private float minmoney;
    private String flightno;
   // @NotNull
    private float driverlevel;
   // @NotNull
    private float timecost;
   // @NotNull
    private float drivertime;
   // @NotNull
    private int cartype;
    private String cartypename;
    private float overdistance;
    private float overcost;
    private float highcost;
    private float parkingcost;
   // @Generated(hash = 1765081515)
    public Order(Long id, int ordertime, Integer orderid, String code, int type, int status,
                 float price, float tip, float startingcost, float settlementcost, float discountcost,
                 String waitingtime, float waitingcost, String registrationId, String photo,
                 String startingtime, String beginplacedescription, String beginlocation,
                 String arrivingtime, String endplacedescription, String endlocation, Integer driverid,
                 String drivername, String driverphone, String drivercode, Integer memberid,
                 String memberphone, String membername, int ordertype, String totaltime, String memo,
                 String goods, int isevaluation, String paytype, int score, float distance,
                 float distancecost, String description, String plate, String carmodel, String addTime,
                 String beginTime, String ordertypename, String bookingtime, int rownumber, float nightcost,
                 float minmoney, String flightno, float driverlevel, float timecost, float drivertime,
                 int cartype, String cartypename, float overdistance, float overcost, float highcost,
                 float parkingcost) {
        this.id = id;
        this.ordertime = ordertime;
        this.orderid = orderid;
        this.code = code;
        this.type = type;
        this.status = status;
        this.price = price;
        this.tip = tip;
        this.startingcost = startingcost;
        this.settlementcost = settlementcost;
        this.discountcost = discountcost;
        this.waitingtime = waitingtime;
        this.waitingcost = waitingcost;
        this.registrationId = registrationId;
        this.photo = photo;
        this.startingtime = startingtime;
        this.beginplacedescription = beginplacedescription;
        this.beginlocation = beginlocation;
        this.arrivingtime = arrivingtime;
        this.endplacedescription = endplacedescription;
        this.endlocation = endlocation;
        this.driverid = driverid;
        this.drivername = drivername;
        this.driverphone = driverphone;
        this.drivercode = drivercode;
        this.memberid = memberid;
        this.memberphone = memberphone;
        this.membername = membername;
        this.ordertype = ordertype;
        this.totaltime = totaltime;
        this.memo = memo;
        this.goods = goods;
        this.isevaluation = isevaluation;
        this.paytype = paytype;
        this.score = score;
        this.distance = distance;
        this.distancecost = distancecost;
        this.description = description;
        this.plate = plate;
        this.carmodel = carmodel;
        this.addTime = addTime;
        this.beginTime = beginTime;
        this.ordertypename = ordertypename;
        this.bookingtime = bookingtime;
        this.rownumber = rownumber;
        this.nightcost = nightcost;
        this.minmoney = minmoney;
        this.flightno = flightno;
        this.driverlevel = driverlevel;
        this.timecost = timecost;
        this.drivertime = drivertime;
        this.cartype = cartype;
        this.cartypename = cartypename;
        this.overdistance=overdistance;
        this.overcost=overcost;
        this.highcost=highcost;
        this.parkingcost=parkingcost;
    }
   // @Generated(hash = 1105174599)
    public Order() {
    }
    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public int getOrdertime() {
        return this.ordertime;
    }
    public void setOrdertime(int ordertime) {
        this.ordertime = ordertime;
    }
    public Integer getOrderid() {
        return this.orderid;
    }
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
    public String getCode() {
        return this.code;
    }
    public void setCode(String code) {
        this.code = code;
    }
    public int getType() {
        return this.type;
    }
    public void setType(int type) {
        this.type = type;
    }
    public int getStatus() {
        return this.status;
    }
    public void setStatus(int status) {
        this.status = status;
    }
    public float getPrice() {
        return this.price;
    }
    public void setPrice(float price) {
        this.price = price;
    }
    public float getTip() {
        return this.tip;
    }
    public void setTip(float tip) {
        this.tip = tip;
    }
    public float getStartingcost() {
        return this.startingcost;
    }
    public void setStartingcost(float startingcost) {
        this.startingcost = startingcost;
    }
    public float getSettlementcost() {
        return this.settlementcost;
    }
    public void setSettlementcost(float settlementcost) {
        this.settlementcost = settlementcost;
    }
    public float getDiscountcost() {
        return this.discountcost;
    }
    public void setDiscountcost(float discountcost) {
        this.discountcost = discountcost;
    }
    public String getWaitingtime() {
        return this.waitingtime;
    }
    public void setWaitingtime(String waitingtime) {
        this.waitingtime = waitingtime;
    }
    public float getWaitingcost() {
        return this.waitingcost;
    }
    public void setWaitingcost(float waitingcost) {
        this.waitingcost = waitingcost;
    }
    public String getRegistrationId() {
        return this.registrationId;
    }
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }
    public String getPhoto() {
        return this.photo;
    }
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getStartingtime() {
        return this.startingtime;
    }
    public void setStartingtime(String startingtime) {
        this.startingtime = startingtime;
    }
    public String getBeginplacedescription() {
        return this.beginplacedescription;
    }
    public void setBeginplacedescription(String beginplacedescription) {
        this.beginplacedescription = beginplacedescription;
    }
    public String getBeginlocation() {
        return this.beginlocation;
    }
    public void setBeginlocation(String beginlocation) {
        this.beginlocation = beginlocation;
    }
    public String getArrivingtime() {
        return this.arrivingtime;
    }
    public void setArrivingtime(String arrivingtime) {
        this.arrivingtime = arrivingtime;
    }
    public String getEndplacedescription() {
        return this.endplacedescription;
    }
    public void setEndplacedescription(String endplacedescription) {
        this.endplacedescription = endplacedescription;
    }
    public String getEndlocation() {
        return this.endlocation;
    }
    public void setEndlocation(String endlocation) {
        this.endlocation = endlocation;
    }
    public Integer getDriverid() {
        return this.driverid;
    }
    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }
    public String getDrivername() {
        return this.drivername;
    }
    public void setDrivername(String drivername) {
        this.drivername = drivername;
    }
    public String getDriverphone() {
        return this.driverphone;
    }
    public void setDriverphone(String driverphone) {
        this.driverphone = driverphone;
    }
    public String getDrivercode() {
        return this.drivercode;
    }
    public void setDrivercode(String drivercode) {
        this.drivercode = drivercode;
    }
    public Integer getMemberid() {
        return this.memberid;
    }
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }
    public String getMemberphone() {
        return this.memberphone;
    }
    public void setMemberphone(String memberphone) {
        this.memberphone = memberphone;
    }
    public String getMembername() {
        return this.membername;
    }
    public void setMembername(String membername) {
        this.membername = membername;
    }
    public int getOrdertype() {
        return this.ordertype;
    }
    public void setOrdertype(int ordertype) {
        this.ordertype = ordertype;
    }
    public String getTotaltime() {
        return this.totaltime;
    }
    public void setTotaltime(String totaltime) {
        this.totaltime = totaltime;
    }
    public String getMemo() {
        return this.memo;
    }
    public void setMemo(String memo) {
        this.memo = memo;
    }
    public String getGoods() {
        return this.goods;
    }
    public void setGoods(String goods) {
        this.goods = goods;
    }
    public int getIsevaluation() {
        return this.isevaluation;
    }
    public void setIsevaluation(int isevaluation) {
        this.isevaluation = isevaluation;
    }
    public String getPaytype() {
        return this.paytype;
    }
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }
    public int getScore() {
        return this.score;
    }
    public void setScore(int score) {
        this.score = score;
    }
    public float getDistance() {
        return this.distance;
    }
    public void setDistance(float distance) {
        this.distance = distance;
    }
    public float getDistancecost() {
        return this.distancecost;
    }
    public void setDistancecost(float distancecost) {
        this.distancecost = distancecost;
    }
    public String getDescription() {
        return this.description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPlate() {
        return this.plate;
    }
    public void setPlate(String plate) {
        this.plate = plate;
    }
    public String getCarmodel() {
        return this.carmodel;
    }
    public void setCarmodel(String carmodel) {
        this.carmodel = carmodel;
    }
    public String getAddTime() {
        return this.addTime;
    }
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }
    public String getBeginTime() {
        return this.beginTime;
    }
    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }
    public String getOrdertypename() {
        return this.ordertypename;
    }
    public void setOrdertypename(String ordertypename) {
        this.ordertypename = ordertypename;
    }
    public String getBookingtime() {
        return this.bookingtime;
    }
    public void setBookingtime(String bookingtime) {
        this.bookingtime = bookingtime;
    }
    public int getRownumber() {
        return this.rownumber;
    }
    public void setRownumber(int rownumber) {
        this.rownumber = rownumber;
    }
    public float getNightcost() {
        return this.nightcost;
    }
    public void setNightcost(float nightcost) {
        this.nightcost = nightcost;
    }
    public float getMinmoney() {
        return this.minmoney;
    }
    public void setMinmoney(float minmoney) {
        this.minmoney = minmoney;
    }
    public String getFlightno() {
        return this.flightno;
    }
    public void setFlightno(String flightno) {
        this.flightno = flightno;
    }
    public float getDriverlevel() {
        return this.driverlevel;
    }
    public void setDriverlevel(float driverlevel) {
        this.driverlevel = driverlevel;
    }
    public float getTimecost() {
        return this.timecost;
    }
    public void setTimecost(float timecost) {
        this.timecost = timecost;
    }
    public float getDrivertime() {
        return this.drivertime;
    }
    public void setDrivertime(float drivertime) {
        this.drivertime = drivertime;
    }
    public int getCartype() {
        return this.cartype;
    }
    public void setCartype(int cartype) {
        this.cartype = cartype;
    }
    public String getCartypename() {
        return this.cartypename;
    }
    public void setCartypename(String cartypename) {
        this.cartypename = cartypename;
    }

    public float getOverdistance() {
        return overdistance;
    }

    public void setOverdistance(float overdistance) {
        this.overdistance = overdistance;
    }

    public float getOvercost() {
        return overcost;
    }

    public void setOvercost(float overcost) {
        this.overcost = overcost;
    }

    public float getHighcost() {
        return highcost;
    }

    public void setHighcost(float highcost) {
        this.highcost = highcost;
    }

    public float getParkingcost() {
        return parkingcost;
    }

    public void setParkingcost(float parkingcost) {
        this.parkingcost = parkingcost;
    }


}
