/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_base_nativeUtil_NativeUtils */

#ifndef _Included_com_base_nativeUtil_NativeUtils
#define _Included_com_base_nativeUtil_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_base_nativeUtil_NativeUtils
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_base_nativeUtil_NativeUtils_getNativeString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
